# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'WYNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WYNews

pod 'SDWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYModel'
pod 'FMDB'

  target 'WYNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
